name: Pyright Type Check

on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  type-check:
    name: Check Python Types with Pyright
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyright
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi

      - name: Run Pyright
        run: pyright backend/app --level error
