name: Format Frontend Code With ESLint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - staging
    paths:
      - "frontend/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Fail if package-lock.json exists
        run: |
          if [ -f frontend/package-lock.json ]; then
            echo "Error: package-lock.json is present. Remove it and use pnpm instead.";
            exit 1;
          fi

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: frontend

      - name: Run ESLint
        run: pnpm lint
        working-directory: frontend

      - name: Commit and push changes if formatting is needed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "refactor: format frontend code with ESLint"
          file_pattern: "frontend/"
